import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { FiArrowLeft, FiArrowUpRight, FiCheck, FiHeart, FiMapPin, FiMessageCircle, FiShield, FiStar, FiUsers } from 'react-icons/fi';
import NavBar from '../../components/Navbar/NavBar';
import Footer from '../../components/Footer/Footer';

const hostelDetails = {
	'the-nest-residency': { name: 'The Nest Residency', location: 'Koramangala, Bengaluru', college: 'Christ University', price: 'Rs. 8,500', rating: '4.8', reviews: '126', image: 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1400&q=85', type: 'Private rooms and co-living', commute: '12 min to Christ University', description: 'A bright, well-connected stay for students who want the energy of Koramangala close by and a comfortable place to come back to.', amenities: ['Wi-Fi', 'Housekeeping', 'Power backup', 'Study lounge', 'Meals available', '24/7 security'] },
	'campus-cove': { name: 'Campus Cove', location: 'Hinjewadi, Pune', college: 'Symbiosis Institute', price: 'Rs. 7,200', rating: '4.7', reviews: '98', image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1400&q=85', type: 'Shared rooms and co-living', commute: '8 min to Symbiosis Institute', description: 'A practical, social home base in Hinjewadi with the essentials sorted for a smooth college routine.', amenities: ['Wi-Fi', 'Laundry', 'Gym access', 'Common kitchen', 'Parking', 'CCTV'] },
	'olive-house': { name: 'Olive House', location: 'Madhapur, Hyderabad', college: 'IIIT Hyderabad', price: 'Rs. 9,000', rating: '4.9', reviews: '151', image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1400&q=85', type: 'Premium co-living', commute: '15 min to IIIT Hyderabad', description: 'A calm, thoughtfully designed co-living space in Madhapur with room to focus, recharge, and meet your people.', amenities: ['Wi-Fi', 'Daily meals', 'Rooftop', 'Fitness room', 'Study lounge', 'Housekeeping'] },
	'the-green-room': { name: 'The Green Room', location: 'Salt Lake, Kolkata', college: 'IEM Kolkata', price: 'Rs. 6,800', rating: '4.6', reviews: '74', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85', type: 'Student hostel', commute: '10 min to IEM Kolkata', description: 'An easy, value-focused stay in Salt Lake for students who want a simple commute and a welcoming community.', amenities: ['Wi-Fi', 'Meals available', 'Laundry', 'Power backup', 'CCTV', 'Common room'] },
	'north-star-living': { name: 'North Star Living', location: 'New Town, Kolkata', college: 'Techno India', price: 'Rs. 7,900', rating: '4.8', reviews: '62', image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85', type: 'Modern co-living', commute: '9 min to Techno India', description: 'A new-on-Homies stay with clean lines, flexible rooms, and a quick route to New Town campuses.', amenities: ['Wi-Fi', 'Study desks', 'Laundry', 'Security', 'Common kitchen', 'Parking'] },
	'maple-co-live': { name: 'Maple Co-Live', location: 'Viman Nagar, Pune', college: 'MIT World Peace University', price: 'Rs. 8,100', rating: '4.7', reviews: '88', image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1400&q=85', type: 'Shared apartments', commute: '14 min to MIT World Peace University', description: 'A move-in-ready shared apartment for students who want privacy, connection, and a well-placed Pune address.', amenities: ['Wi-Fi', 'Fully furnished', 'Housekeeping', 'Security', 'Power backup', 'Bike parking'] },
	'casa-nook': { name: 'Casa Nook', location: 'HSR Layout, Bengaluru', college: 'Christ University', price: 'Rs. 12,800', rating: '4.8', reviews: '103', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85', type: 'Private rooms', commute: '18 min to Christ University', description: 'A comfortable private-room option in HSR Layout with the space and calm to settle into your next chapter.', amenities: ['Wi-Fi', 'Fully furnished', 'Laundry', 'Security', 'Study desks', 'Common area'] },
	'mango-tree-living': { name: 'Mango Tree Living', location: 'Indiranagar, Bengaluru', college: 'Christ University', price: 'Rs. 11,500', rating: '4.7', reviews: '67', image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85', type: 'Shared apartments', commute: '16 min to Christ University', description: 'A leafy shared stay in Indiranagar with generous common spaces and a relaxed community feel.', amenities: ['Wi-Fi', 'Common kitchen', 'Laundry', 'Power backup', 'Security', 'Study lounge'] },
	'the-olive-house': { name: 'The Olive House', location: 'Koramangala, Bengaluru', college: 'Christ University', price: 'Rs. 14,500', rating: '4.9', reviews: '142', image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1400&q=85', type: 'Premium co-living', commute: '12 min to Christ University', description: 'A polished co-living stay in Koramangala with a warm shared atmosphere and everything close at hand.', amenities: ['Wi-Fi', 'Daily meals', 'Gym access', 'Housekeeping', 'Study lounge', '24/7 security'] },
	'the-nest-collective': { name: 'The Nest Collective', location: 'Indiranagar, Bengaluru', college: 'Christ University', price: 'Rs. 10,900', rating: '4.7', reviews: '91', image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1400&q=85', type: 'Shared apartments', commute: '20 min to Christ University', description: 'A community-minded shared apartment in Indiranagar for students who like their city life close and lively.', amenities: ['Wi-Fi', 'Common kitchen', 'Laundry', 'Power backup', 'Security', 'Rooftop'] },
};

const HostelDetails = () => {
	const { hostelId } = useParams();
	const hostel = hostelDetails[hostelId] || hostelDetails['the-nest-residency'];
	const [isSaved, setIsSaved] = useState(false);
	const [enquirySent, setEnquirySent] = useState(false);

	return (
		<>
			<NavBar />
			<main className="hostel-detail-page">
				<div className="hostel-detail-inner"><Link className="hostel-back-link" to="/hostels"><FiArrowLeft aria-hidden="true" /> Back to all hostels</Link>
					<section className="hostel-detail-hero"><div className="hostel-detail-image"><img src={hostel.image} alt={`${hostel.name} accommodation`} /><span><FiShield aria-hidden="true" /> Verified property</span></div><div className="hostel-detail-summary"><p className="hostel-detail-kicker">{hostel.type}</p><h1>{hostel.name}</h1><p className="hostel-detail-location"><FiMapPin aria-hidden="true" /> {hostel.location}</p><div className="hostel-detail-rating"><strong><FiStar aria-hidden="true" /> {hostel.rating}</strong><span>{hostel.reviews} student reviews</span></div><p className="hostel-detail-description">{hostel.description}</p><div className="hostel-detail-price"><strong>{hostel.price}</strong><span>/ month</span></div><div className="hostel-detail-actions"><button className="hostel-enquire-button" type="button" onClick={() => setEnquirySent(true)}><FiMessageCircle aria-hidden="true" /> {enquirySent ? 'Enquiry sent' : 'Contact owner'}</button><button className={isSaved ? 'hostel-save-button saved' : 'hostel-save-button'} type="button" onClick={() => setIsSaved((current) => !current)} aria-label={isSaved ? 'Remove saved hostel' : 'Save hostel'}><FiHeart aria-hidden="true" /></button></div>{enquirySent && <p className="hostel-enquiry-note" role="status"><FiCheck aria-hidden="true" /> The owner will be notified. You can track replies from your dashboard.</p>}</div></section>

					<section className="hostel-detail-content"><div className="hostel-detail-main"><div className="hostel-detail-section"><p className="hostel-detail-kicker">A good fit if you want</p><h2>Less guesswork, more room to settle in.</h2><div className="hostel-detail-highlights"><span><FiMapPin aria-hidden="true" /><strong>Well connected</strong>{hostel.commute}</span><span><FiUsers aria-hidden="true" /><strong>Made for students</strong>Friendly shared spaces</span><span><FiShield aria-hidden="true" /><strong>Verified details</strong>Reviewed by Homies Stay</span></div></div><div className="hostel-detail-section"><p className="hostel-detail-kicker">What is included</p><h2>Everything you need to begin.</h2><div className="hostel-amenities">{hostel.amenities.map((amenity) => <span key={amenity}><FiCheck aria-hidden="true" /> {amenity}</span>)}</div></div></div><aside className="hostel-detail-aside"><p className="hostel-detail-kicker">Have a question?</p><h3>Ask before you decide.</h3><p>Send the owner an enquiry about availability, room types, move-in dates, or anything else on your mind.</p><button type="button" onClick={() => setEnquirySent(true)}>Ask the owner <FiArrowUpRight aria-hidden="true" /></button><small>Typical response within 24 hours</small></aside></section>
				</div>
			</main>
			<Footer />
		</>
	);
};

export default HostelDetails;
